AWSTemplateFormatVersion: "2010-09-09"
Description: Production CodePipeline for Earthquake Lambda Architecture

Parameters:
  GitHubOwner:
    Type: String
    Default: PrathyushaCherukuri

  GitHubRepo:
    Type: String
    Default: earthquake-lambda-architecture

  GitHubBranch:
    Type: String
    Default: main

  GitHubTokenSecret:
    Type: String
    Default: github-token-prathyusha

  ArtifactBucket:
    Type: String
    Default: prathyusha-earthquake-artifacts

Resources:

  # --------------------------------------------------
  # CodeBuild Project
  # --------------------------------------------------
  EarthquakeCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: earthquake-build
      ServiceRole: arn:aws:iam::430006376054:role/service-role/AWSCodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 30

  # --------------------------------------------------
  # CodePipeline
  # --------------------------------------------------
  EarthquakePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: earthquake-production-pipeline
      RoleArn: arn:aws:iam::430006376054:role/service-role/AWSCodePipelineServiceRole
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket

      Stages:

        # -------------------------
        # SOURCE
        # -------------------------
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Sub "{{resolve:secretsmanager:${GitHubTokenSecret}:SecretString:token}}"

        # -------------------------
        # BUILD
        # -------------------------
        - Name: Build
          Actions:
            - Name: BuildArtifacts
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref EarthquakeCodeBuild

        # -------------------------
        # DEPLOY CORE INFRA
        # -------------------------
        - Name: DeployCoreInfra
          Actions:
            - Name: CoreInfra
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: earthquake-core-infra
                TemplatePath: BuildOutput::infra/core-infra.yaml
                Capabilities: CAPABILITY_NAMED_IAM

        # -------------------------
        # DEPLOY LAMBDAS
        # -------------------------
        - Name: DeployLambdas
          Actions:
            - Name: Lambdas
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: earthquake-lambdas
                TemplatePath: BuildOutput::infra/lambdas.yaml
                Capabilities: CAPABILITY_NAMED_IAM

        # -------------------------
        # DEPLOY GLUE
        # -------------------------
        - Name: DeployGlue
          Actions:
            - Name: Glue
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: earthquake-glue
                TemplatePath: BuildOutput::infra/glue.yaml
                Capabilities: CAPABILITY_NAMED_IAM

        # -------------------------
        # DEPLOY STEP FUNCTIONS
        # -------------------------
        - Name: DeployOrchestration
          Actions:
            - Name: StepFunctions
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: earthquake-stepfunctions
                TemplatePath: BuildOutput::infra/stepfunctions.yaml
                Capabilities: CAPABILITY_NAMED_IAM
