AWSTemplateFormatVersion: "2010-09-09"
Description: Earthquake Lambda Architecture - Core (reference existing resources)

Parameters:
  ExistingBucketName:
    Type: String
    Description: Existing S3 bucket for raw/curated/serving data

  KinesisStreamArn:
    Type: String

  KinesisStreamName:
    Type: String

  DynamoTableName:
    Type: String

  DynamoTableArn:
    Type: String

  SnsTopicArn:
    Type: String

  DlqArn:
    Type: String

Outputs:
  BucketName:
    Value: !Ref ExistingBucketName
    Export:
      Name: EarthquakeBucketName

  KinesisStreamArn:
    Value: !Ref KinesisStreamArn
    Export:
      Name: EarthquakeKinesisStreamArn

  KinesisStreamName:
    Value: !Ref KinesisStreamName
    Export:
      Name: EarthquakeKinesisStreamName

  DynamoTableName:
    Value: !Ref DynamoTableName
    Export:
      Name: EarthquakeDynamoTableName

  DynamoTableArn:
    Value: !Ref DynamoTableArn
    Export:
      Name: EarthquakeDynamoTableArn

  SnsTopicArn:
    Value: !Ref SnsTopicArn
    Export:
      Name: EarthquakeAlertsTopicArn

  DlqArn:
    Value: !Ref DlqArn
    Export:
      Name: EarthquakeDlqArn
