AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda functions for Earthquake Lambda Architecture (CloudFormation-first, production-ready)

Parameters:

  # --------------------------------------------------
  # Shared / Existing Resources
  # --------------------------------------------------
  LambdaExecutionRoleArn:
    Type: String
    Description: Existing IAM role ARN for Lambda execution

  ArtifactBucket:
    Type: String
    Description: S3 bucket containing lambda zip artifacts

  # --------------------------------------------------
  # Lambda Artifact Keys (FIXED)
  # --------------------------------------------------
  ProducerZipKey:
    Type: String
    Default: producer.zip

  ConsumerZipKey:
    Type: String
    Default: consumer.zip

  ReplayZipKey:
    Type: String
    Default: replay.zip

  # --------------------------------------------------
  # Core Infra (from core-infra stack)
  # --------------------------------------------------
  KinesisStreamArn:
    Type: String
    Description: Kinesis stream ARN

  KinesisStreamName:
    Type: String
    Description: Kinesis stream name

  DynamoTableName:
    Type: String
    Description: DynamoDB latest-state table name

  SnsTopicName:
    Type: String
    Description: SNS alerts topic name

  DlqArn:
    Type: String
    Description: SQS Dead Letter Queue ARN

  DlqUrl:
    Type: String
    Description: SQS Dead Letter Queue URL

Resources:

  # ==================================================
  # Producer Lambda
  # ==================================================
  EarthquakeProducerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: earthquake-producer
      Runtime: python3.9
      Handler: app.lambda_handler
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref ProducerZipKey
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          KINESIS_STREAM_NAME: !Ref KinesisStreamName
          USGS_URL: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson

  # ==================================================
  # Consumer Lambda
  # ==================================================
  EarthquakeConsumerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: earthquake-consumer
      Runtime: python3.9
      Handler: app.lambda_handler
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref ConsumerZipKey
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref DynamoTableName
          SNS_TOPIC_NAME: !Ref SnsTopicName
          RAW_S3_PREFIX: earthquake-lambda-architecture/raw/
          SERVING_S3_PREFIX: earthquake-lambda-architecture/serving/
      DeadLetterConfig:
        TargetArn: !Ref DlqArn

  # ==================================================
  # Kinesis → Consumer Event Mapping
  # ==================================================
  EarthquakeConsumerKinesisMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !Ref KinesisStreamArn
      FunctionName: !Ref EarthquakeConsumerLambda
      StartingPosition: LATEST
      BatchSize: 100
      Enabled: true

  # ==================================================
  # Replay Lambda (DLQ → Kinesis)
  # ==================================================
  EarthquakeReplayLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: earthquake-replay
      Runtime: python3.9
      Handler: app.lambda_handler
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref ReplayZipKey
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          DLQ_URL: !Ref DlqUrl
          KINESIS_STREAM_NAME: !Ref KinesisStreamName

Outputs:

  ProducerLambdaArn:
    Description: Producer Lambda ARN
    Value: !GetAtt EarthquakeProducerLambda.Arn
    Export:
      Name: EarthquakeProducerLambdaArn

  ConsumerLambdaArn:
    Description: Consumer Lambda ARN
    Value: !GetAtt EarthquakeConsumerLambda.Arn
    Export:
      Name: EarthquakeConsumerLambdaArn

  ReplayLambdaArn:
    Description: Replay Lambda ARN
    Value: !GetAtt EarthquakeReplayLambda.Arn
    Export:
      Name: EarthquakeReplayLambdaArn
