AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda functions for Earthquake Lambda Architecture (reuse existing ARNs)

Parameters:

  LambdaExecutionRoleArn:
    Type: String
    Description: Existing IAM role ARN for Lambda & Step Functions

  ArtifactBucket:
    Type: String
    Description: S3 bucket containing lambda zip artifacts

  ProducerZipKey:
    Type: String
    Default: lambdas/producer.zip

  ConsumerZipKey:
    Type: String
    Default: lambdas/consumer.zip

  ReplayZipKey:
    Type: String
    Default: lambdas/replay.zip

  KinesisStreamArn:
    Type: String
    Description: Existing Kinesis stream ARN

  KinesisStreamName:
    Type: String
    Description: Existing Kinesis stream name

  DlqArn:
    Type: String
    Description: Existing DLQ ARN

  DlqUrl:
    Type: String
    Description: Existing DLQ URL

Resources:

  # --------------------------------------------------
  # Producer Lambda
  # --------------------------------------------------
  EarthquakeProducerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: earthquake-producer
      Runtime: python3.9
      Handler: app.lambda_handler
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref ProducerZipKey
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          KINESIS_STREAM_NAME: !Ref KinesisStreamName
          USGS_URL: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson

  # --------------------------------------------------
  # Consumer Lambda
  # --------------------------------------------------
  EarthquakeConsumerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: earthquake-consumer
      Runtime: python3.9
      Handler: app.lambda_handler
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref ConsumerZipKey
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          DDB_TABLE_NAME: earthquake-lambda-architecture-latest
          SNS_TOPIC_NAME: earthquake-lambda-architecture-alerts
          RAW_S3_PREFIX: earthquake-lambda-architecture/raw/
          SERVING_S3_PREFIX: earthquake-lambda-architecture/serving/
      DeadLetterConfig:
        TargetArn: !Ref DlqArn

  # --------------------------------------------------
  # Kinesis → Consumer Trigger
  # --------------------------------------------------
  EarthquakeConsumerKinesisMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !Ref KinesisStreamArn
      FunctionName: !Ref EarthquakeConsumerLambda
      StartingPosition: LATEST
      BatchSize: 100
      Enabled: true

  # --------------------------------------------------
  # Replay Lambda
  # --------------------------------------------------
  EarthquakeReplayLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: earthquake-replay
      Runtime: python3.9
      Handler: app.lambda_handler
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref ReplayZipKey
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          DLQ_URL: !Ref DlqUrl
          KINESIS_STREAM_NAME: !Ref KinesisStreamName
