AWSTemplateFormatVersion: "2010-09-09"
Description: Step Function for replaying failed earthquake events

Resources:

  EarthquakeReplayStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: earthquake-replay-state-machine
      RoleArn: arn:aws:iam::430006376054:role/service-role/StepFunctions-earthquake-batch-orchestration-role-opc1s30hm
      DefinitionString:
        Fn::Sub: |
          {
            "Comment": "Replay failed earthquake events from DLQ back to Kinesis",
            "StartAt": "ReplayFailedEvents",
            "States": {
              "ReplayFailedEvents": {
                "Type": "Task",
                "Resource": "arn:aws:states:::lambda:invoke",
                "Parameters": {
                  "FunctionName": "earthquake-replay"
                },
                "End": true
              }
            }
          }

Outputs:
  ReplayStateMachineArn:
    Description: ARN of the replay Step Function
    Value: !Ref EarthquakeReplayStateMachine
