version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Zipping Lambda functions"
      - mkdir -p dist

      - cd lambdas/producer && zip -r ../../dist/producer.zip . && cd ../..
      - cd lambdas/consumer && zip -r ../../dist/consumer.zip . && cd ../..
      - cd lambdas/replay && zip -r ../../dist/replay.zip . && cd ../..

      - echo "Build completed"

artifacts:
  files:
    - dist/*
    - infra/*
    - glue/*
    - serving/*
