version: 0.2

env:
  variables:
    ARTIFACT_BUCKET: prathyusha-earthquake-artifacts

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Packaging Lambda functions"
      - mkdir -p dist

      - zip -r dist/producer.zip lambdas/producer
      - zip -r dist/consumer.zip lambdas/consumer
      - zip -r dist/replay.zip lambdas/replay

      - echo "Uploading Lambda artifacts to S3"
      - aws s3 cp dist/producer.zip s3://$ARTIFACT_BUCKET/producer.zip
      - aws s3 cp dist/consumer.zip s3://$ARTIFACT_BUCKET/consumer.zip
      - aws s3 cp dist/replay.zip   s3://$ARTIFACT_BUCKET/replay.zip

artifacts:
  files:
    - infra/**/*
