version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Packaging Lambda functions"
      - mkdir -p artifacts

      - zip -r artifacts/producer.zip lambdas/producer
      - zip -r artifacts/consumer.zip lambdas/consumer
      - zip -r artifacts/replay.zip lambdas/replay

      - echo "Build completed"

artifacts:
  files:
    - artifacts/*
    - infra/*
    - glue/*
    - serving/*
