AWSTemplateFormatVersion: "2010-09-09"
Description: Production CodePipeline for Earthquake Lambda Architecture

Resources:

  EarthquakePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: earthquake-production-pipeline

      ArtifactStore:
        Type: S3
        Location: prathyusha-earthquake-artifacts

      Stages:

        # ==================================================
        # SOURCE
        # ==================================================
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: PrathyushaCherukuri
                Repo: earthquake-lambda-architecture
                Branch: main
                OAuthToken: "{{resolve:secretsmanager:github-token-prathyusha:SecretString:token}}"
              RunOrder: 1

        # ==================================================
        # BUILD
        # ==================================================
        - Name: Build
          Actions:
            - Name: BuildArtifacts
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: earthquake-build
              RunOrder: 1

        # ==================================================
        # DEPLOY CORE / STREAMING
        # ==================================================
        - Name: DeployStreaming
          Actions:
            - Name: DeployStreamingStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: earthquake-core-infra
                TemplatePath: BuildOutput::infra/core-infra.yaml
                Capabilities: CAPABILITY_NAMED_IAM
              RunOrder: 1

        # ==================================================
        # DEPLOY LAMBDAS
        # ==================================================
        - Name: DeployLambdas
          Actions:
            - Name: DeployLambdaStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: earthquake-lambdas
                TemplatePath: BuildOutput::infra/lambdas.yaml
                Capabilities: CAPABILITY_NAMED_IAM
                ParameterOverrides: |
                  {
                    "LambdaExecutionRoleArn": "arn:aws:iam::430006376054:role/earthquake-stepfunction-s-ConsumerLambdaExecutionRo-pmNzOHWiNlBD",
                    "ArtifactBucket": "prathyusha-earthquake-artifacts",
                    "KinesisStreamArn": "arn:aws:kinesis:eu-west-2:430006376054:stream/earthquake-lambda-architecture-stream",
                    "KinesisStreamName": "earthquake-lambda-architecture-stream",
                    "DynamoTableName": "earthquake-lambda-architecture-latest",
                    "SnsTopicName": "earthquake-lambda-architecture-alerts",
                    "DlqArn": "arn:aws:sqs:eu-west-2:430006376054:earthquake-lambda-architecture-dlq",
                    "DlqUrl": "https://sqs.eu-west-2.amazonaws.com/430006376054/earthquake-lambda-architecture-dlq"
                  }
              RunOrder: 1

        # ==================================================
        # DEPLOY GLUE
        # ==================================================
        - Name: DeployGlue
          Actions:
            - Name: DeployGlueStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: earthquake-glue
                TemplatePath: BuildOutput::infra/glue.yaml
                Capabilities: CAPABILITY_NAMED_IAM
              RunOrder: 1

        # ==================================================
        # DEPLOY STEP FUNCTIONS
        # ==================================================
        - Name: DeployOrchestration
          Actions:
            - Name: DeployStepFunctionsStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: earthquake-stepfunctions
                TemplatePath: BuildOutput::infra/stepfunctions.yaml
                Capabilities: CAPABILITY_NAMED_IAM
              RunOrder: 1
